site_name: LAMPrEY Documentation
nav:
    - Home: index.md
    - Setup:
        - Installation: installation.md
        - Admin panel: how-to-access-the-admin-panel.md
    - Usage:
        - Create a project: how-to-add-a-project.md
        - Create a pipeline: how-to-add-a-pipeline.md
        - Submit RAW files: how-to-submit-raw-files.md
    - Components:
        - Datalake: datalake.md
        - RawTools: rawtools.md
        - MaxQuant: maxquant.md
    - Resources:
        - API: api.md
        - About: about.md
        - Help/Issues: issues.md
extra:
  analytics:
      provider: google
      property: G-3B0G926SJ2   
repo_name: LAMPrEY
repo_url: https://github.com/LewisResearchGroup/ProteomicsQC
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
