# Generated by Django 5.2.11 on 2026-03-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxquant', '0020_rawfile_owner_aware_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxquantexecutable',
            options={'verbose_name': 'MaxQuant Version', 'verbose_name_plural': 'MaxQuant Versions'},
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='maxquant_executable',
            field=models.FilePathField(blank=True, help_text='If this field is empty the default MaxQuant version (2.0.3.0) will be used. To try a different version go to MaxQuant Executables. If this is changed, all MaxQuant jobs in this pipeline should be rerun.', match='.*MaxQuantCmd\\.(exe|dll)', max_length=2000, null=True, path='/compute', recursive=True),
        ),
    ]
